#!/bin/sh
set -o errexit
set -o nounset

main() {
    echo "removing old deploy zip & clearing build dir"
    rm -rf dist
    echo "compiling source files"
    ./node_modules/.bin/esbuild src/worker.ts \
      --platform=node \
      --bundle \
      --minify \
      --sourcemap \
      --loader:.png=file \
      --target=es2020,safari11 \
      --outdir=dist \
      '--define:process.env.NODE_ENV="production"'
    echo "done"
}

main "$@"
